[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/robots"
  to = "/robots.txt"
  status = 301

# Gestion 404 - DOIT ÊTRE LA DERNIÈRE RÈGLE
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  condition = "Status != 200"
